
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID LBRACE RBRACE SEMICOLON STRUCT TYPE TYPEDEF\n    declaration : STRUCT ID LBRACE fields RBRACE SEMICOLON\n                | TYPEDEF STRUCT ID LBRACE fields RBRACE ID SEMICOLON\n             \n    \n    fields : TYPE ID SEMICOLON fields\n           | TYPE ID SEMICOLON\n    '
    
_lr_action_items = {'STRUCT':([0,3,],[2,5,]),'TYPEDEF':([0,],[3,]),'$end':([1,14,19,],[0,-1,-2,]),'ID':([2,5,9,16,],[4,7,12,18,]),'LBRACE':([4,7,],[6,10,]),'TYPE':([6,10,15,],[9,9,9,]),'RBRACE':([8,13,15,17,],[11,16,-4,-3,]),'SEMICOLON':([11,12,18,],[14,15,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'fields':([6,10,15,],[8,13,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> STRUCT ID LBRACE fields RBRACE SEMICOLON','declaration',6,'p_declaration','structuredecleration.py',58),
  ('declaration -> TYPEDEF STRUCT ID LBRACE fields RBRACE ID SEMICOLON','declaration',8,'p_declaration','structuredecleration.py',59),
  ('fields -> TYPE ID SEMICOLON fields','fields',4,'p_fields','structuredecleration.py',66),
  ('fields -> TYPE ID SEMICOLON','fields',3,'p_fields','structuredecleration.py',67),
]
